[project]
name = "ga4-bq-dbt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt-bigquery>=1.10.1",
    "dbt-core>=1.10.7",
]
